# 24-bit PCM too quiet, using 16-bit as workaround
monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-sound"
        api.alsa.card.name = "PocketMax"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
  {
    matches = [
      {
        alsa.card_name = "PocketMax"
        api.alsa.path = "hw:PocketMax,0"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
