#!/bin/bash
set -uo pipefail

sysfs_root=${ARMADA_SYSFS_ROOT:-/sys}

case "$1/$2" in
    pre/*)
        echo serial1-0 | tee "$sysfs_root/bus/serial/devices/serial1/subsystem/drivers/rsinput/unbind"
        ;;
    post/*)
        echo serial1-0 | tee "$sysfs_root/bus/serial/devices/serial1/subsystem/drivers/rsinput/bind"
        ;;
esac