#!/bin/bash
# Forces PipeWire sinks to suspend before s2idle to allow Qualcomm ADSP to collapse.

case "$1" in
    pre)
        systemctl --user --machine="armada@" stop pipewire.socket pipewire.service pipewire-pulse.socket pipewire-pulse.service wireplumber.service
        ;;
    post)
        systemctl --user --machine="armada@" start pipewire.socket pipewire.service pipewire-pulse.socket pipewire-pulse.service wireplumber.service
        ;;
esac