#!/bin/bash
# Forces PipeWire sinks to suspend before s2idle to allow Qualcomm ADSP to collapse.

case "$1" in
    pre)
        systemctl --user --machine=$USER@ stop wireplumber.service
    post)
        systemctl --user --machine=$USER@ start wireplumber.service
esac
